security:
  gitops:
    caf_landingzone_branch: int-5.6.0

  relative_destination_folder: level1/security

  tfstate:
    lz_key_name: security
    tfstate: security.tfstate
    level: level1
    identity_aad_key: cred_management
    config_file: security.yaml
    # Do not rename the tfstate_key_name
    tfstate_key_name: security

  deployments:
    landingzone:
      global_settings_key:
        platform:
          launchpad:
      remote_tfstates:
        platform:
          launchpad:

  resources:
    security:
      resource_groups:
        management:
          name: management
        alerts:
          name: alerts

      monitor_action_groups:
        security_operations:
          action_group_name: Security Operations
          resource_group_key: alerts
          shortname: secops
          arm_role_alert:
            reader:
              name: Monitoring Reader
              role_name: Monitoring Reader
              use_common_alert_schema: false
          email_receiver:
            noc:
              name: email_alert_support1
              email_address: email@address.com
              use_common_alert_schema: false

      service_health_alerts:
        enable_service_health_alerts: true
        name: alerts
        shortname: HealthAlerts
        resource_group_key: alerts
        action_group_name: actiongrp
        email_alert_settings:
          support1:
            name: email_alert_support1
            email_address: email@address.com
            use_common_alert_schema: false

      recovery_vaults:
        asr:
          name: asr
          resource_group_key: management
          soft_delete_enabled: true
          backup_policies:
            vms:
              default:
                backup:
                  frequency: Daily
                  time: '23:00'
                name: vm-default-policy
                retention_daily:
                  count: 7
                retention_monthly:
                  count: 2
                  weekdays:
                  - Sunday
                  weeks:
                  - First
                retention_weekly:
                  count: 2
                  weekdays:
                  - Sunday
                retention_yearly:
                  count: 1
                  months:
                  - January
                  weekdays:
                  - Sunday
                  weeks:
                  - First
                timezone: SE Asia Standard Time
